import Head from 'next/head'
import MainLayout from '@/components/Layouts/MainLayout'
import HomePage from '@/components/pages/HomePage'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainLayout>
        <HomePage />
      </MainLayout>

    </>
  )
}
